### ISSUE TITLE
Why is LinkedHashSet used here?

### ISSUE THREAD

**Issue by hohserg1** [sockeqwe/annotationprocessing101#11]
Hello! Your article is very good, thx for this)
I don't really understand why is `LinkedHashSet` used in `getSupportedAnnotationTypes`, can you explain this moment?
https://github.com/sockeqwe/annotationprocessing101/blob/master/factory/processor/src/main/java/com/hannesdorfmann/annotationprocessing101/factory/processor/FactoryProcessor.java#L67

**Comment by sockeqwe** [comment]
Hi, thanks for your feedback.
I'm sorry but I really don't remember why I have used `LinkedHashSet`.  I doubt that it had a deeper meaning. It works with any `Set` implementation.
