### ISSUE TITLE
文章有个错误的地方

### ISSUE THREAD

**Issue by DanielYP** [sockeqwe/annotationprocessing101#6]
public void setA (  // ExecuteableElement
                     int newA   // TypeElement
) {}

// ----------

int newA 的Element类型应该是 TypeParameterElement

**Comment by sockeqwe** [comment]
What is your question? What issue do you face?

DanielYP <notifications@github.com> schrieb am Di., 16. Mai 2017, 17:00:

**Comment by DanielYP** [comment]
i think the article has a error

```
public void setA ( // ExecuteableElement
   int newA // TypeElement
) {}
```

`int newA` is not a `TyepElement`,its a `TypeParameterElement`

**Comment by DanielYP** [comment]
#
