### ISSUE TITLE
How to open this repo using IDEA ?

### ISSUE THREAD

**Issue by CoXier** [sockeqwe/annotationprocessing101#9]

**Comment by sockeqwe** [comment]
What exactly is the problem?

JianxinLi <notifications@github.com> schrieb am Fr., 1. Dez. 2017, 04:28:

**Comment by CoXier** [comment]
Here is question link https://stackoverflow.com/questions/47586054/how-to-open-pom-xml-project-using-idea

**Comment by sockeqwe** [comment]
Just use the open dialog in intellij and open the pom.xml file in the root
folder of this project.

JianxinLi <notifications@github.com> schrieb am Fr., 1. Dez. 2017, 14:43:

**Comment by CoXier** [comment]
Obviously there is not pom.xml in your root folder of this project.

**Comment by sockeqwe** [comment]
Oops, you are right. Open the pom.xml file in the favtory folder. That is
the project that contains the annotation and the annotation processor.
https://github.com/sockeqwe/annotationprocessing101/tree/master/factory

To build the annotation processor you have to run mvn install in this
folder
https://github.com/sockeqwe/annotationprocessing101/tree/master/factory

Then you can open use the annotation processor and annotations in other
projects like
https://github.com/sockeqwe/annotationprocessing101/tree/master/factory-sample/pizzastore
did (open the pom.xml file in this directory in IntelliJ, its a separate
project not part of the annotation processor project).

JianxinLi <notifications@github.com> schrieb am Sa., 2. Dez. 2017, 04:45:
